services:
  # Backend API Service
  - type: web
    name: recruitment-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: recruitment-db
          property: connectionString
    healthCheckPath: /health

  # Frontend Web Service
  - type: web
    name: recruitment-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: recruitment-db
    plan: free

